
package ficctos;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.lang.System.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author daniel
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    
    private Object ultimoClick;
    public MainForm() {
        initComponents();
        this.setResizable(false);
        int x =Toolkit.getDefaultToolkit().getScreenSize().width;
        int y=Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setSize((3*x)/4, (3*y)/4);
        this.setLocation(x/2- ((3*x)/4)/2,y/2 -((3*y)/4)/2);
        this.setTitle("FICCT-OS App");   
        initTabbedPaneComponents();
        iniciarDescripcion();
        this.jButton2= iniciarBoton(this.jButton2,10,10);

    }
    
    private javax.swing.JButton iniciarBoton(javax.swing.JButton b,int posx,int posy){
        int x = 5*this.getWidth()/8;
        int y =this.getHeight();
        b.setName("nuevo");
        b.setBounds(posx,posy, y/5,y/5);
        Image img= new ImageIcon(getClass().getClassLoader().getResource("recursos/imagenes/iconos/lazarus_icon112.png")).getImage();
        ImageIcon img2 = new ImageIcon(img.getScaledInstance(b.getWidth()/2,b.getHeight()/2, Image.SCALE_DEFAULT));
        b.setIcon(img2);
        b.setBorderPainted(false);
        b.setHorizontalTextPosition(b.CENTER);
        b.setVerticalTextPosition(b.BOTTOM);
        b.setFont(new Font("Italic", Font.PLAIN, 18));
        b.setForeground(Color.WHITE);
        b.setContentAreaFilled(false);
        img2 = new ImageIcon(img.getScaledInstance(b.getWidth()*3/4,b.getHeight()*3/4, Image.SCALE_DEFAULT));
        b.setPressedIcon(img2);
        
      //  b.setBackground(Color.BLACK);
        return b;
    }

    private void initTabbedPaneComponents(){
        jTabbedPane1.setBounds(0,0,5*this.getWidth()/8,this.getHeight());
        int meta = jTabbedPane1.getComponentCount();
        javax.swing.JPanel panel;
        
        Image img= new ImageIcon(getClass().getClassLoader().getResource("recursos/imagenes/background/background.png")).getImage();
        
        ImageIcon img2; 
        javax.swing.JLabel label;
        
        String names[] ={"1er Semestre","2do Semestre","3er Semestre","4to Semestre","5to Semestre"};
        for (int i=0; i<meta;i++){
          panel = (javax.swing.JPanel)jTabbedPane1.getComponent(i);
          panel.setBounds(0,0,jTabbedPane1.getWidth(),jTabbedPane1.getHeight());
          img2 = new ImageIcon(img.getScaledInstance(panel.getWidth(),panel.getHeight(), Image.SCALE_DEFAULT));
          label = new javax.swing.JLabel();
          panel.add(label);
          label.setBounds(0,0,panel.getWidth(),panel.getHeight());
          label.setIcon(img2);
          jTabbedPane1.setTitleAt(i, names[i]);
          
          
        }

    }
    

    public void iniciarDescripcion(){
        
        jPanel5.setBounds(5*this.getWidth()/8, 0,3*this.getWidth()/8,this.getHeight());
        int a = jPanel5.getWidth()/8;
        jLabel1.setBounds(a,a,jPanel5.getWidth()-2*a,(jPanel5.getHeight()-3*a)/3);
        Image img= new ImageIcon(getClass().getClassLoader().getResource("recursos/imagenes/iconos/ficctOs.png")).getImage();
        ImageIcon img2 = new ImageIcon(img.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(img2);
        jScrollPane1.setBounds(a,2*a+jLabel1.getHeight(), jPanel5.getWidth()-2*a,jPanel5.getHeight()-3*a-jLabel1.getHeight());
        jButton1.setBounds(a,a+jLabel1.getHeight(), jPanel5.getWidth()-2*a,a);
        jButton1.setText("Iniciar");
        jButton1.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton2.setText("Lazarus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 30, 63, 28);

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel3.setLayout(null);
        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel2.setLayout(null);
        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel4.setLayout(null);
        jTabbedPane1.addTab("tab4", jPanel4);

        jPanel6.setLayout(null);
        jTabbedPane1.addTab("tab5", jPanel6);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 60, 300, 160);

        jPanel5.setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(5);
        jTextArea1.setText("Esta aplicacion fue desarrollada\npor el grupo de estudiantes\nparte del nucleoLinuxUagrm\nde la facultad de Cs de la\ncomputacion y telecomunicaciones.\nPara tener un mejor \nacceso a las aplicaciones \npreinstaladas en la distribucion\nFicctOs , y facilitar el uso a los\nestudiantes.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 280, 170);

        jLabel1.setText("jLabel1");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(70, 40, 120, 50);

        jButton1.setText("jButton1");
        jPanel5.add(jButton1);
        jButton1.setBounds(80, 100, 70, 28);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(340, 20, 300, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                try {
            /*   try
            {
            File file = new File("/home/daniel/Escritorio/android.desktop");
            if(!Desktop.isDesktopSupported())
            {
            System.out.println("not supported");
            return;
            }
            Desktop desktop = Desktop.getDesktop();
            if(file.exists())
            desktop.open(file);
            
            }
            catch(Exception e)
            {
            e.printStackTrace();
            System.out.println("Error al abrir el archivo");
            }*/  
            String path = "$HOME/.lazarus/bin/lazarus";
            String[] command = {"exec",path};
            Process process = Runtime.getRuntime().exec(command);
        } catch (IOException ex) {
            jTextArea1.setText("no existe el archivo");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    private javax.swing.JButton nuevo;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
